name: wiki_places
description: WikiPo app.

publish_to: 'none'
version: 2.0.2+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  firebase_core: ^1.8.0
  firebase_analytics: ^8.3.4
  firebase_crashlytics: ^2.6.2
  sentry_flutter: ^6.5.1
  cross_connectivity: any
  cupertino_icons: ^1.0.2
  sorted_list: ^1.0.0
  geolocator: ^8.2.0
  webview_flutter: ^3.0.2
  google_maps_flutter: ^2.0.1
  google_fonts: ^2.3.1
  loading_overlay: ^0.3.0
  flutter_native_splash: ^2.1.6
  flutter_typeahead: ^4.0.0
  shared_preferences: ^2.0.15
  another_flushbar: ^1.10.29
  flutter_launcher_icons: ^0.9.2
  expandable: ^5.0.1
  convex_bottom_bar: ^3.0.0
  introduction_screen: ^3.0.2
  rating_dialog: ^2.0.3
  share_plus: ^4.0.7
  mailer: ^5.1.1

flutter_native_splash:
  background_image: "images/start_app.png"

flutter_icons:
  image_path: "images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/app_icon_android.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/walkthrough/he/
